min_distance_from_cursor_to_bottom = 4
default_file_editor_command = ["vim", "<FILE>"]

[global_key_bindings]
q = "quit"
"/" = "search_mode"
ESC = "normal_mode"
[normal_mode_key_bindings]
ESC = "remove_marks"
ENTER = "apply_mark_action"
d = "toggle_delete_mark"

r = "rename"
x = "delete_instantly"

i = "create_file"
I = "create_directory"

h = "left"
j = "down"
k = "up"
l = "right"

G = "go_to_or_go_to_bottom"
"g g" = "go_to_top"

[text_input_mode_key_bindings]
q = "noop"
"/" = "noop"
BACKSPACE = "delete_last_char"
ENTER = "select"
