preview_text_length = 100

[global_key_bindings]
q = "quit"
"/" = "search_mode"
ESC = "normal_mode"
[normal_mode_key_bindings]
h = "left"
j = "down"
k = "up"
l = "right"
G = "go_to_or_go_to_bottom"
"g g" = "go_to_top"
[search_mode_key_bindings]
q = "noop"
BACKSPACE = "delete_last_char"
ENTER = "select"
